# https://medium.com/swlh/auto-deploying-a-monorepo-to-heroku-with-github-actions-da62e8ae172c
name: Deploy to Heroku (Backend)

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add backend remote origin
        run: git remote add heroku-loctastic-backend https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/loctastic-backend.git
      - name: Deploy backend to Heroku
        run: git push heroku-loctastic-backend `git subtree split --prefix backend main`:refs/heads/main --force